// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueryValidatorRepository is an autogenerated mock type for the QueryValidatorRepository type
type QueryValidatorRepository struct {
	mock.Mock
}

// EnsureNonEmptyQuery provides a mock function with given fields: query
func (_m *QueryValidatorRepository) EnsureNonEmptyQuery(query string) error {
	ret := _m.Called(query)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueryValidatorRepository creates a new instance of QueryValidatorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryValidatorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryValidatorRepository {
	mock := &QueryValidatorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
